### ISSUE TITLE
question: what about $PATH2PROJ?

### ISSUE THREAD

**Issue by thendarion** [jason-fox/fox.jason.extend.css#4]
why not just `{$PATH2PROJ}` instead of `{$relpath}/`?

https://github.com/jason-fox/fox.jason.extend.css/blob/c348a5abf8ab3613f81fe1df129b4eb5d5f8b72b/Customization/xsl/extended-css.xsl#L39

**Comment by jason-fox** [comment]
The [initial revision](https://github.com/jason-fox/fox.jason.extend.css/blob/65df26c03d461e9723e5f2b098cda1870c9c5a5b/Customization/xsl/extended-css.xsl) did indeed use `{$PATH2PROJ}`  

```xml
<xsl:template match="/|node()|@*" mode="gen-common-extended-style">
     <xsl:variable name="urltest" as="xs:boolean"> <!-- test for URL -->
        <xsl:call-template name="url-string">
          <xsl:with-param name="urltext" select="concat($CSSPATH, $EXTENDED-CSS)"/>
        </xsl:call-template>
      </xsl:variable>

     <xsl:choose>
        <xsl:when test="$urltest">
          <link rel="stylesheet" type="text/css" href="{$CSSPATH}{$EXTENDED-CSS}" />
        </xsl:when>
        <xsl:otherwise>
          <link rel="stylesheet" type="text/css" href="{$PATH2PROJ}{$CSSPATH}{$EXTENDED-CSS}" />
        </xsl:otherwise>
      </xsl:choose>
  </xsl:template>
```

Unfortunately this simple solution didn't work with all relative placements of the topics compared to the ditamap.

I can't remember which one, but one of the [unit-tests](https://github.com/jason-fox/fox.jason.extend.css/tree/master/test) ended up with the css `<link>` header pointing to the wrong location, so I replaced it with a relative path which worked for that use case as well.

**Comment by thendarion** [comment]
thanks :)

on the other hand, it would be good to know which scenario made PATH2PROJ fail to point to the right folder. since it's an integral part of DITA-OT, this bug might affect other parts as well
