### ISSUE TITLE
Potential Filepath issue when using Windows

### ISSUE THREAD

**Issue by jason-fox** [jason-fox/fox.jason.extend.css#5]
Related https://github.com/infotexture/dita-bootstrap/issues/56

> Hello,
> 
> I founded a displaying issue with topics at level 3 and more :
> 
> ![image](https://user-images.githubusercontent.com/37327034/193012789-b41ec37b-7393-4438-bf88-3692ef5bd17c.png)
> 
> Used command line: `dita -i "C:\xxx\inputs\flowers\flowers.ditamap" -t "C:\xxx\inputs\flowers\temp" -o "C:\xxx\inputs\flowers\out" -f=html5-bootstrap -v --menubar-toc.include=no --args.breadcrumbs=yes --nav-toc=collapsible`
> 
> Input and output are here: [flowers.zip](https://github.com/infotexture/dita-bootstrap/files/9673974/flowers.zip)
> 
> Thanks.

**Comment by jason-fox** [comment]
@Nico-Amplexor - could you run your transform with a `-d` flag and tell me what value windows is passing for `$FILEDIR`

Maybe something like this will work:

```xml
 <xsl:variable name="relpath">
      <xsl:choose>
        <xsl:when test="$FILEDIR='.'">
          <xsl:text>.</xsl:text>
        </xsl:when>
        <xsl:when test="contains($FILEDIR,'\')" >
           <xsl:value-of select=" replace($FILEDIR,'[^\\]+','..')"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:value-of select=" replace($FILEDIR,'[^/]+','..')"/>
        </xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
```

**Comment by Nico-Amplexor** [comment]
@jason-fox, please find here the log with `-d` flag 
[log-boostrap-win.txt](https://github.com/jason-fox/fox.jason.extend.css/files/9713378/log-boostrap-win.txt)

**Comment by jason-fox** [comment]
Could you try this update e4786899 to see if it has fixed it:

```console
dita uninstall jason.fox.extend.css
dita install https://github.com/jason-fox/jason.fox.extend.css/archive/master.zip
```

**Comment by Nico-Amplexor** [comment]
@jason-fox , it works well now with your fix 👍
