### ISSUE TITLE
Customizing the **common-extended.css** file

### ISSUE THREAD

**Issue by jason-fox** [jason-fox/fox.jason.extend.css#6]
Related https://github.com/infotexture/dita-bootstrap/issues/57 @Billy-102 wrote:

> I want to customize the **common-extended.css** file in the output dir, but I did not find the source file in the plugin **fox.jason.extend.css**, could you please give me some clue?

**Comment by jason-fox** [comment]
`common-extended` is a generated file. This plugin offers a series of [Extension Points](https://github.com/jason-fox/fox.jason.extend.css#extension-points) to allow plugins to add CSS to it.

Within your own custom plugin, just append extra CSS as shown:

```xml
<loadfile property="extra.css" srcFile="/path/to/css"/>
<echo append="true" message="${line.separator}${extra.css}" file="${extend.css.file}"/>
```

**Comment by bing-10** [comment]
I just want to modify some lines in the original common-extended.css, is there any easier way to change the source?

**Comment by jason-fox** [comment]
Not that easily. Within the  dita-bootstrap plugin [multiple CSS files](https://github.com/infotexture/dita-bootstrap/tree/develop/css) may or may not be added depending upon the type of layout required. You could perhaps edit those files directly, but then your plugin would diverge from the main development branch. It would be more sustainable to add your changes as an extra plugin to be called after dita-bootstrap. However, the CSS in `common-extended.css` is designed to be layout only, not basic look-and-feel.

Of course the dita-bootstrap plug-in already supports the standard DITA-OT parameters to inject additional CSS for look-and-feel which is placed **after** `common-extended.css` as described [here](https://github.com/infotexture/dita-bootstrap#custom-css)

```console
dita --input=path/to/your.ditamap --format=html5-bootstrap \
     --args.hdr=path/to/your-header.xml \
     --args.css=<name-of-css>.css \
     --args.copycss=yes \
     --args.csspath=css \
     --args.cssroot=path/to/your/theme
```

An example can be found in [infotexture.github.io](https://infotexture.github.io/dita-bootstrap/typography.html) where the CSS for the box around each example can be found [here](https://github.com/infotexture/dita-bootstrap/blob/develop/.github/dita-ot/theme.css#L18-L23)

**Comment by bing-10** [comment]
Thank you for your advice, I will refer to it later.



---- Replied Message ----
| From | Jason ***@***.***> |
| Date | 10/25/2022 20:02 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [jason-fox/fox.jason.extend.css] Customizing the **common-extended.css** file (Issue #6) |

Not that easily. Within the dita-bootstrap plugin multiple CSS files may or may not be added depending upon the type of layout required. You could perhaps edit those files directly, but then your plugin would diverge from the main development branch. It would be more sustainable to add your changes as an extra plugin to be called after dita-bootstrap. However, the CSS in common-extended.css is designed to be layout only, not basic look-and-feel.

Of course the dita-bootstrap plug-in already supports the standard DITA-OT parameters to inject additional CSS for look-and-feel which is placed aftercommon-extended.css as described here

dita --input=path/to/your.ditamap --format=html5-bootstrap \     --args.hdr=path/to/your-header.xml \     --args.css=<name-of-css>.css \     --args.copycss=yes \     --args.csspath=css \     --args.cssroot=path/to/your/theme

An example can be found in infotexture.github.io where the CSS for the box around each example can be found here

**Comment by jason-fox** [comment]
Closing
