### ISSUE TITLE
Placing args.css file as the last CSS link

### ISSUE THREAD

**Issue by lakokkonen** [jason-fox/fox.jason.extend.css#7]
Hi again,

(I'm not sure whether this should be addressed in the DITA Bootstrap repo or in this one, but let's start here...)

When building output with the DITA Bootstrap plugin, the common-extended.css file is inserted after the CSS file defined with the DITA-OT args.css parameter, in the HTML head.

This means that the common-extended.css overrides CSS properties defined in the args.css file, if they have the same specificity. Additionally, since some things in the common-extended.css have the !important property set to them, the user can't change them at all.

Would it be possible to have the args.css file set as the last CSS link?

**Comment by jason-fox** [comment]
That would be simple to fix.Just move the call to `<xsl:apply-templates select="." mode="gen-common-extended-style"/>` from the bottom to the top of the file.

**Comment by lakokkonen** [comment]
That did indeed work, thank you!
